// ===== Settings · Data: export a JSON backup, import one (claude.ai copy ⇄ hosted copy) =====
const IMPORT_SKIP = ["users", "dashboards"];
function pDataTab() { const P = V.impData; const cols = P ? Object.keys(P.data || {}).filter(c => Array.isArray(P.data[c])) : []; const rows = cols.map(c => [c, P.data[c].length, IMPORT_SKIP.includes(c) ? "skipped" : c === "audit" ? "appended" : "imported"]); const total = rows.filter(r => r[2] !== "skipped").reduce((a, r) => a + r[1], 0);
  return `<div class="grid"><div class="card s6"><div class="topbar"><b>Export</b>${qi("Everything this workspace holds, as one JSON file: plans, forecasts, streams, documents, settings, the activity log. Set the client picker to All clients first for a complete backup.")}</div><div class="lab">Downloads a backup of the data currently in view${V.ws ? ` (client filter applied: <b>${esc(wsName(byId("clients", V.ws)) || V.ws)}</b>; choose All clients for everything)` : " (all clients)"}. Keep it with the plan, or import it into another copy of the Hub.</div><div class="sec-h" style="margin-top:12px"><button class="btn" data-a="backup">Download backup (JSON)</button></div></div>
  <div class="card s6"><div class="topbar"><b>Import</b>${qi("Restores a backup made by any copy of the Hub. Records with the same id are overwritten, new ones are added, nothing else is deleted. Users and per-profile dashboards are skipped because accounts differ between copies; activity-log rows are appended.")}</div><div class="lab">Pick a backup file from this Hub or from the claude.ai copy. Nothing is written until you confirm.</div><div class="dropzone" style="margin-top:12px"><input type="file" id="imp_file" accept=".json,application/json" style="display:block;width:100%"></div>
  ${P ? `<div class="lab" style="margin-top:10px"><b>${esc(V.impName || "backup")}</b> · exported ${esc(String(P.exported || "").slice(0, 16).replace("T", " "))} · workspace ${esc(P.workspace || "all")}</div><table style="margin-top:8px"><thead><tr><th>Collection</th><th class="num">Records</th><th>Action</th></tr></thead><tbody>${rows.map(([c, n, a]) => `<tr><td class="mono">${esc(c)}</td><td class="num">${n}</td><td class="lab">${a}</td></tr>`).join("")}</tbody></table><div class="tfoot">${rows.length} collections · ${total} records to write</div><div class="sec-h" style="margin-top:10px"><button class="btn" data-a="import_go" ${total ? "" : "disabled"}>Import ${total} records</button><button class="btn ghost" data-a="import_clear">Clear</button></div>` : ""}</div></div>`; }
async function importBackup(P) { if (!DB) return toast("Storage is not available in this view."); const cols = Object.keys(P.data || {}).filter(c => Array.isArray(P.data[c]) && !IMPORT_SKIP.includes(c)); let total = 0, done = 0; cols.forEach(c => { total += P.data[c].length; }); const t0 = Date.now();
  for (const c of cols) { const docs = P.data[c].filter(d => d && d.id != null).map(d => strip(d)); if (!COLS.includes(c)) COLS.push(c); if (!S[c]) S[c] = []; if (!docs.length) continue;
    if (typeof DB.bulk === "function") { const base = done; done += await DB.bulk(c, docs, n => toast(`Importing ${c}: ${n} of ${docs.length} · ${base + n} of ${total}`)); }
    else { let i = 0; const worker = async () => { while (i < docs.length) { const d = docs[i++]; await DB.doc(`${c}/${d.id}`).set(d); done++; if (done % 20 === 0) toast(`Importing ${c}… ${done} of ${total}`); } }; await Promise.all(Array.from({length: 6}, worker)); } }
  await loadAll(); V.impData = null; V.impName = ""; await logActivity("backup_import", `${done} records in ${cols.length} collections from a backup exported ${P.exported || "unknown"}`); render(); toast(`Imported ${done} records into ${cols.length} collections in ${Math.round((Date.now() - t0) / 1000)}s`); }
document.addEventListener("change", e => { const f = e.target; if (f.id !== "imp_file" || !f.files || !f.files[0]) return; const file = f.files[0]; const r = new FileReader(); r.onload = () => { try { const P = JSON.parse(r.result); if (!P || typeof P !== "object" || !P.data || typeof P.data !== "object") throw new Error("shape"); V.impData = P; V.impName = file.name; render(); } catch (_) { V.impData = null; toast("That file is not an Analytics Hub backup."); render(); } }; r.readAsText(file); });
document.addEventListener("click", async e => { const b = e.target.closest('[data-a="import_go"],[data-a="import_clear"]'); if (!b) return; if (b.dataset.a === "import_clear") { V.impData = null; V.impName = ""; render(); return; } const P = V.impData; if (!P) return; const n = Object.keys(P.data).filter(c => Array.isArray(P.data[c]) && !IMPORT_SKIP.includes(c)).reduce((a, c) => a + P.data[c].length, 0); if (!confirm(`Import ${n} records into this Hub? Records with the same id are overwritten; nothing else is deleted.`)) return; b.disabled = true; try { await importBackup(P); } catch (err) { toast("Import failed: " + (err.message || err.code || err)); render(); } });
