
// ===== Dashboard layout engine v1.0 — a free 12-column grid: drag a widget by its title bar to move it, pull its right edge, bottom edge or corner to resize; the other widgets slide out of the way and pack upward; the layout is saved per dashboard =====
const DL = {cols: 12, rowH: 30, gap: 22, minW: 3, minH: 4};
const DL_KIND_H = {tracker: 8, breakout: 9, notice: 7, chart: 9, table: 10, tiles: 6, calendar: 12, list: 9, text: 8};
const dlOverlap = (a, b) => a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;
const dlUnit = () => DL.rowH + DL.gap;
const dlClamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
function dlFirstFit(placed, w, h) { for (let y = 0; y < 4000; y++) for (let x = 0; x + w <= DL.cols; x++) { const c = {x, y, w, h}; if (!placed.some(p => dlOverlap(c, p))) return c; } return {x: 0, y: 0, w, h}; }
function dlDefaultSize(w) { const T = WIDGETS[w.type] || {}; const units = w.w === 2 || (w.w == null && T.w === 2) ? 12 : 6; const h = T.h || DL_KIND_H[T.kind] || (w.type === "text" ? 8 : T.cat === "measure" ? 9 : 8); return {w: units, h}; }
// migrate half/full widgets (w = 1 | 2) to units and place anything unplaced by first fit; returns true when the doc changed
function dlEnsure(D) { const W = D.widgets || []; let changed = false; const placed = W.filter(w => Number.isInteger(w.x) && Number.isInteger(w.y) && Number.isInteger(w.h) && w.w >= DL.minW); for (const w of W) { if (placed.includes(w)) continue; const s = dlDefaultSize(w); const c = dlFirstFit(placed, s.w, s.h); Object.assign(w, c); placed.push(w); changed = true; } for (const w of W) { const nw = dlClamp(w.w, DL.minW, DL.cols), nh = Math.max(DL.minH, w.h), nx = dlClamp(w.x, 0, DL.cols - nw), ny = Math.max(0, w.y); if (nw !== w.w || nh !== w.h || nx !== w.x || ny !== w.y) { Object.assign(w, {x: nx, y: ny, w: nw, h: nh}); changed = true; } } return changed; }
// pack upward: items keep their reading order (top to bottom, left to right); `fixed` stays where it is and everything else flows around it; `priority` wins ties
function dlCompact(items, fixed = null, priority = null) { const order = items.slice().sort((a, b) => a.y - b.y || (a === priority ? -1 : b === priority ? 1 : a.x - b.x)); const placed = fixed ? [fixed] : []; for (const it of order) { if (it === fixed) continue; let y = 0; while (placed.some(p => p !== it && dlOverlap({x: it.x, w: it.w, h: it.h, y}, p))) y++; it.y = y; placed.push(it); } return items; }
const dlHeight = items => Math.max(0, ...items.map(i => i.y + i.h)) * dlUnit() - DL.gap;
function dlStyle(w) { const u = dlUnit(); return `left:calc((100% + ${DL.gap}px) * ${w.x} / ${DL.cols});width:calc((100% + ${DL.gap}px) * ${w.w} / ${DL.cols} - ${DL.gap}px);top:${w.y * u}px;height:${w.h * u - DL.gap}px`; }
function dlApply(grid, D) { for (const w of D.widgets) { const el = grid.querySelector(`[data-wid="${w.id}"]`); if (el) { el.style.cssText = dlStyle(w); } } grid.style.height = Math.max(0, dlHeight(D.widgets)) + "px"; }
let DL_SAVE_T = null; function dlSaveSoon(D) { clearTimeout(DL_SAVE_T); DL_SAVE_T = setTimeout(() => { dashSave(D).catch(e => console.error(e)); }, 350); }
function dlCard(w, edit) { const T = WIDGETS[w.type]; if (!T) return ""; let body = ""; try { body = T.render(w.cfg || {}, w); } catch (e) { body = `<div class="lab">Could not render: ${esc(e.message)}</div>`; }
  return `<div class="card widget" data-wid="${w.id}" style="${dlStyle(w)}"><div class="topbar wdrag" ${edit ? 'title="Drag to move · pull the right edge, bottom edge or corner to resize"' : ""}>${edit ? `<span class="grip" aria-hidden="true">⋮⋮</span>` : ""}<b>${esc(w.title || T.name)}</b>${qi(T.desc)}<span class="spacer"></span>${edit ? `<div class="btngrp"><button class="btn ghost xs" data-dw="up" data-v="${w.id}" title="Move earlier in reading order">↑</button><button class="btn ghost xs" data-dw="down" data-v="${w.id}" title="Move later in reading order">↓</button><button class="btn ghost xs" data-dw="fit" data-v="${w.id}" title="Fit the height to the content">Fit</button><button class="btn ghost xs" data-dw="size" data-v="${w.id}">${w.w >= DL.cols ? "Half width" : "Full width"}</button>${T.cfg?.length || w.type === "text" ? `<button class="btn ghost xs" data-dw="cfg" data-v="${w.id}">Configure</button>` : ""}<button class="btn ghost xs" data-dw="rm" data-v="${w.id}">Remove</button></div>` : ""}</div><div class="wbody">${body}</div>${edit ? `<span class="rz e" data-rz="e" title="Resize width"></span><span class="rz s" data-rz="s" title="Resize height"></span><span class="rz se" data-rz="se" title="Resize width and height"></span>` : ""}</div>`; }
function dashGridHtml(D, edit) { if (dlEnsure(D)) dlSaveSoon(D); const W = D.widgets || []; return `<div class="grid dash free ${edit ? "editing" : ""}" id="dashgrid" style="height:${Math.max(0, dlHeight(W))}px">${W.map(w => dlCard(w, edit)).join("")}</div>${edit ? `<div class="lab" style="margin-top:8px">Drag a widget by its title bar to move it; pull its right edge, bottom edge or corner to resize it. The others slide out of the way and pack upward. Changes save as you go.</div>` : ""}`; }
function dlReorder(D, w, dir) { const order = D.widgets.slice().sort((a, b) => a.y - b.y || a.x - b.x); const i = order.indexOf(w); const j = i + dir; if (j < 0 || j >= order.length) return; order.splice(i, 1); order.splice(j, 0, w); const placed = []; for (const it of order) { Object.assign(it, dlFirstFit(placed, it.w, it.h)); placed.push(it); } }
function dlFit(D, w) { const el = document.querySelector(`#dashgrid [data-wid="${w.id}"]`); const body = el?.querySelector(".wbody"); if (!el || !body) return; const extra = el.getBoundingClientRect().height - body.getBoundingClientRect().height; const px = body.scrollHeight + extra; w.h = Math.max(DL.minH, Math.ceil((px + DL.gap) / dlUnit())); dlCompact(D.widgets, null, w); }
// --- pointer interactions (edit mode only)
let DLDRAG = null;
document.addEventListener("pointerdown", e => { if (e.button !== 0 && e.pointerType === "mouse") return; const grid = e.target.closest?.("#dashgrid.editing"); if (!grid) return; const rz = e.target.closest("[data-rz]"); let handle = rz; if (!handle) { const bar = e.target.closest(".wdrag"); if (bar && !e.target.closest("button,a,input,select,textarea,[data-qi],[data-qi-html]")) handle = bar; } if (!handle) return; const card = handle.closest(".widget"); const id = card?.dataset.wid; const g = dashGroup(); const D = dashDoc(g); const w = D?.widgets.find(x => x.id === id); if (!w) return; e.preventDefault(); const rect = grid.getBoundingClientRect(); const colW = (rect.width + DL.gap) / DL.cols; const u = dlUnit(); const ph = document.createElement("div"); ph.className = "wph"; ph.style.cssText = dlStyle(w); grid.appendChild(ph); card.classList.add("dragging"); grid.classList.add("live"); DLDRAG = {mode: rz ? rz.dataset.rz : "move", id, D, w, start: {x: e.clientX, y: e.clientY}, orig: {x: w.x, y: w.y, w: w.w, h: w.h}, target: {x: w.x, y: w.y, w: w.w, h: w.h}, colW, u, grid, card, ph, handle, preview: null}; try { handle.setPointerCapture(e.pointerId); } catch (err) { /* older browsers */ } });
function dlPreview(S) { const items = S.D.widgets.map(w => w.id === S.id ? {...S.target, id: w.id} : {x: w.x, y: w.y, w: w.w, h: w.h, id: w.id}); const moved = items.find(i => i.id === S.id); dlCompact(items, moved); S.ph.style.cssText = dlStyle(moved); for (const it of items) { if (it.id === S.id) continue; const el = S.grid.querySelector(`[data-wid="${it.id}"]`); if (el) el.style.cssText = dlStyle(it); } S.preview = items; S.grid.style.height = Math.max(0, dlHeight(items), (S.target.y + S.target.h) * S.u - DL.gap) + "px"; }
document.addEventListener("pointermove", e => { const S = DLDRAG; if (!S) return; const dx = e.clientX - S.start.x, dy = e.clientY - S.start.y; let t; if (S.mode === "move") { S.card.style.transform = `translate(${dx}px, ${dy}px)`; t = {x: dlClamp(Math.round(S.orig.x + dx / S.colW), 0, DL.cols - S.orig.w), y: Math.max(0, Math.round(S.orig.y + dy / S.u)), w: S.orig.w, h: S.orig.h}; } else { const nw = S.mode === "s" ? S.orig.w : dlClamp(Math.round(S.orig.w + dx / S.colW), DL.minW, DL.cols - S.orig.x); const nh = S.mode === "e" ? S.orig.h : Math.max(DL.minH, Math.round(S.orig.h + dy / S.u)); t = {x: S.orig.x, y: S.orig.y, w: nw, h: nh}; if (S.mode !== "s") S.card.style.width = Math.max(DL.minW * S.colW - DL.gap, Math.min((DL.cols - S.orig.x) * S.colW - DL.gap, S.orig.w * S.colW - DL.gap + dx)) + "px"; if (S.mode !== "e") S.card.style.height = Math.max(DL.minH * S.u - DL.gap, S.orig.h * S.u - DL.gap + dy) + "px"; }
  if (t.x !== S.target.x || t.y !== S.target.y || t.w !== S.target.w || t.h !== S.target.h) { S.target = t; dlPreview(S); } });
function dlEnd(commit) { const S = DLDRAG; if (!S) return; DLDRAG = null; S.card.classList.remove("dragging"); S.card.style.transform = ""; S.ph.remove(); try { S.handle.releasePointerCapture?.(); } catch (err) {} const moved = (S.target.x !== S.orig.x || S.target.y !== S.orig.y || S.target.w !== S.orig.w || S.target.h !== S.orig.h); if (commit && moved && S.preview) { for (const it of S.preview) { const w = S.D.widgets.find(x => x.id === it.id); if (w) Object.assign(w, {x: it.x, y: it.y, w: it.w, h: it.h}); } dlCompact(S.D.widgets, null, S.w); dlSaveSoon(S.D); } dlApply(S.grid, S.D); S.grid.classList.remove("live"); }
document.addEventListener("pointerup", () => dlEnd(true)); document.addEventListener("pointercancel", () => dlEnd(false));
