
// ===== Account picker v1.0 — the client / line-of-business chooser as a panel that hangs off the toolbar (Google Ads / Datorama style) instead of native selects =====
const apLob = c => c ? (c.lob || c.name || "") : "";
function apClients(q) { const names = clientNames(); const n = norm(q || ""); return n ? names.filter(x => norm(x).includes(n) || wsOfClient(x).some(c => norm(apLob(c)).includes(n))) : names; }
function apPanelHtml(where) { const cn = currentClient(); const q = V.apQ || ""; const hover = V.apHover && clientNames().includes(V.apHover) ? V.apHover : cn; const clients = apClients(q); const ws = hover ? wsOfClient(hover).filter(c => !q || norm(apLob(c)).includes(norm(q)) || norm(hover).includes(norm(q))) : []; const cmp = hover && compareEnabled(hover);
  return `<div class="aps"><span class="sic">${ICON("search")}</span><input id="ap_q" placeholder="Search clients and lines of business" value="${esc(q)}" autocomplete="off"></div><div class="apcols"><div class="apcol"><div class="aph">Clients <span class="lab">${clients.length}</span></div><a class="apitem ${!cn ? "on" : ""}" data-ap="client" data-v="">All clients <span class="lab">every workspace</span></a>${clients.map(n => `<a class="apitem ${cn === n ? "on" : ""} ${hover === n ? "hov" : ""}" data-ap="client" data-v="${esc(n)}" data-aphover="${esc(n)}"><span>${esc(n)}</span><span class="lab">${wsOfClient(n).length} LOB${wsOfClient(n).length === 1 ? "" : "s"}</span><span class="car"></span></a>`).join("") || `<div class="lab" style="padding:8px 12px">No client matches.</div>`}</div><div class="apcol"><div class="aph">${hover ? esc(hover) + " · lines of business" : "Lines of business"}</div>${hover ? `${cmp ? `<a class="apitem ${cn === hover && !V.ws ? "on" : ""}" data-ap="ws" data-v="" data-client="${esc(hover)}">All LOBs · combined</a>` : ""}${ws.map(c => `<a class="apitem ${V.ws === c.id ? "on" : ""}" data-ap="ws" data-v="${c.id}" data-client="${esc(hover)}"><span>${esc(apLob(c))}</span>${c.needs_rf === false ? `<span class="lab">no R&amp;F</span>` : ""}</a>`).join("") || `<div class="lab" style="padding:8px 12px">No workspaces yet — add one in Settings → Clients &amp; workspaces.</div>`}` : `<div class="lab" style="padding:8px 12px">Point at a client to see its lines of business. Only that client's LOBs are listed — nothing from other clients.</div>`}</div></div>`; }
function clientPickerHtml() { const cn = currentClient(); const c = V.ws ? byId("clients", V.ws) : null; return `<div class="apick" id="apick"><button class="apbtn" data-ap="toggle" type="button" title="Client and line of business — filters every page"><span class="k">${cn ? "Client" : "Scope"}</span><b>${esc(cn || "All clients")}</b>${cn ? `<span class="sep">›</span><b class="lob">${esc(c ? apLob(c) : (compareEnabled(cn) ? "All LOBs" : ""))}</b>` : ""}<span class="car"></span></button><div class="appanel" id="appanel" ${V.apOpen ? "" : "hidden"}>${V.apOpen ? apPanelHtml("top") : ""}</div></div>`; }
function lobPickerHtml() { const cn = currentClient(); const c = V.ws ? byId("clients", V.ws) : null; const ws = cn ? wsOfClient(cn) : []; const cmp = cn && compareEnabled(cn);
  return `<div class="lobp lobp2"><label>${cn ? "Line of business" : "Workspace"}</label>${cn ? `<div class="lobs">${cmp ? `<a class="lobi ${!V.ws ? "on" : ""}" data-ap="ws" data-v="" data-client="${esc(cn)}">All LOBs · combined</a>` : ""}${ws.map(x => `<a class="lobi ${V.ws === x.id ? "on" : ""}" data-ap="ws" data-v="${x.id}" data-client="${esc(cn)}">${esc(apLob(x))}</a>`).join("")}</div>${!cmp && ws.length > 1 ? `<span class="lab" style="font-size:10.5px">Compare LOBs side by side: switch it on per workspace in Settings → Clients &amp; workspaces</span>` : ""}` : `<a class="lobi" data-ap="toggle">${esc(c ? apLob(c) : "All workspaces")} <span class="lab">choose a client ›</span></a>`}</div>`; }
function apRepaint() { const p = document.getElementById("appanel"); if (p && V.apOpen) p.innerHTML = apPanelHtml("top"); }
document.addEventListener("click", e => { const a = e.target.closest("[data-ap]"); if (!a) { if (V.apOpen && !e.target.closest("#apick")) { V.apOpen = false; const p = document.getElementById("appanel"); if (p) { p.hidden = true; p.innerHTML = ""; } } return; } const k = a.dataset.ap, v = a.dataset.v;
  if (k === "toggle") { V.apOpen = !V.apOpen; V.apQ = ""; V.apHover = null; const p = document.getElementById("appanel"); if (!p) { render(); return; } p.hidden = !V.apOpen; p.innerHTML = V.apOpen ? apPanelHtml("top") : ""; if (V.apOpen) setTimeout(() => document.getElementById("ap_q")?.focus(), 30); return; }
  if (k === "client") { V.client = v; const ws = v ? wsOfClient(v) : []; if (!v || ws.length <= 1) { pickWorkspace(ws.length && !compareEnabled(v) ? ws[0].id : ""); V.apOpen = false; render(); return; } V.apHover = v; pickWorkspace(""); render(); V.apOpen = true; const p = document.getElementById("appanel"); if (p) { p.hidden = false; p.innerHTML = apPanelHtml("top"); } return; }
  if (k === "ws") { const cn = a.dataset.client; if (cn && V.client !== cn) V.client = cn; pickWorkspace(v); V.apOpen = false; render(); return; } });
document.addEventListener("mouseover", e => { const a = e.target.closest?.("[data-aphover]"); if (!a || !V.apOpen) return; if (V.apHover === a.dataset.aphover) return; V.apHover = a.dataset.aphover; const q = document.getElementById("ap_q"); const at = q ? [q.selectionStart, q.selectionEnd] : null; apRepaint(); if (at && document.activeElement !== document.getElementById("ap_q")) { const q2 = document.getElementById("ap_q"); if (q2) { q2.focus(); q2.setSelectionRange(at[0], at[1]); } } });
document.addEventListener("input", e => { if (e.target.id !== "ap_q") return; V.apQ = e.target.value; const at = [e.target.selectionStart, e.target.selectionEnd]; apRepaint(); const q = document.getElementById("ap_q"); if (q) { q.focus(); q.setSelectionRange(at[0], at[1]); } });
document.addEventListener("keydown", e => { if (e.key === "Escape" && V.apOpen) { V.apOpen = false; const p = document.getElementById("appanel"); if (p) { p.hidden = true; p.innerHTML = ""; } } });
