
// ===== Reports v3 — Active reports per client (name + cadence → weekly list, monthly list, month/week calendar) and the QA / Interpret landings (platform tiles → templatized report types → upload | old reports → field map) =====
// Report types the Hub knows per platform. v: true = the report type is named in a reachable official source (checked on WIZ_CHECKED); the export column names stay working names unless the platform dictionary marks them verified.
const RT = (key, label, desc, intents, fields, v, src) => ({key, label, desc, intents, fields, v, src});
const REPORT_TYPES = {
  cm360: [RT("standard", "Standard report", "Delivery by day, site, placement and creative: impressions, clicks, click rate, cost, Active View, conversions.", ["qa", "delivery", "facts"], ["Date", "Advertiser", "Campaign", "Site (CM360)", "Placement", "Placement ID", "Creative", "Impressions", "Clicks", "Click Rate", "Media Cost", "Active View: Viewable Impressions", "Active View: Measurable Impressions", "Total Conversions"], true, "Report type STANDARD in the CM360 Reporting API v4 discovery document"), RT("reach", "Reach report (Unique Reach)", "Modelled unique reach per site or campaign for the window: total, exclusive, duplicate, average frequency, sample size.", ["interpret", "rf"], ["Site (CM360)", "Campaign", "Impressions", "Unique Reach: Total Reach", "Unique Reach: Exclusive Reach", "Unique Reach: Duplicate Reach", "Unique Reach: Impression Reach", "Unique Reach: Average Impression Frequency", "Unique Reach Sample Size", "— (dash)"], true, "Report type REACH with reachByFrequencyMetricNames; all dimension combinations limited to the last 42 days (discovery document)"), RT("cross_dimension_reach", "Cross-dimension reach (overlap)", "Pairwise overlap: people reached by BOTH members of each site or campaign pair.", ["interpret"], ["Site A · Site B · Overlap", "Unique Reach: Total Reach"], true, "Report type CROSS_DIMENSION_REACH pivoting ADVERTISER, CAMPAIGN, SITE_BY_ADVERTISER or SITE_BY_CAMPAIGN with overlap metrics (discovery document)"), RT("floodlight", "Floodlight report", "Conversions by Floodlight activity and configuration.", ["qa"], ["Date", "Advertiser", "Campaign", "Total Conversions"], true, "Report type FLOODLIGHT keyed on dfa:floodlightConfigId (discovery document)"), RT("path_to_conversion", "Path to conversion", "Per-interaction conversion paths.", ["qa"], ["Date", "Campaign", "Total Conversions"], true, "Report type PATH_TO_CONVERSION with per-interaction dimensions (discovery document)")],
  dv360: [RT("standard", "Standard report", "Delivery by insertion order, line item and creative: impressions, clicks, cost, Active View, video views.", ["qa", "delivery", "facts"], ["Date", "Advertiser", "Insertion Order", "Line Item", "Creative", "Impressions", "Clicks", "Click Rate (CTR)", "Total Media Cost (Advertiser Currency)", "Active View: Viewable Impressions", "TrueView: Views", "Complete Views (Video)"], true, "Report type STANDARD in the Bid Manager API v2 discovery document"), RT("reach", "Reach report", "Unique reach and average frequency per insertion order or line item, Google inventory only, 92-day max.", ["interpret", "rf"], ["Insertion Order", "Line Item", "Impressions", "Unique Reach: Total Reach", "Unique Reach: Impression Reach", "Unique Reach: Average Impression Frequency", "Co-viewed Reach"], true, "Report type REACH (discovery document)"), RT("unique_reach_audience", "Unique reach audience", "Reach by audience composition.", ["interpret"], ["Insertion Order", "Unique Reach: Total Reach", "Unique Reach: Average Impression Frequency"], true, "Report type UNIQUE_REACH_AUDIENCE (discovery document)"), RT("grp", "GRP report", "Gross rating points for TV-style planning.", ["qa"], ["Insertion Order", "Line Item", "Impressions"], true, "Report type GRP (discovery document)"), RT("youtube", "YouTube report", "YouTube and partners delivery and views.", ["qa"], ["Insertion Order", "Line Item", "Impressions", "TrueView: Views", "Complete Views (Video)"], true, "Report type YOUTUBE (discovery document)")],
  google_ads: [RT("campaign", "Campaign / ad group report", "Search and YouTube delivery: impressions, clicks, cost, CTR, conversions, view rates.", ["qa", "delivery"], ["segments.date / Day", "campaign.name / Campaign", "ad_group.name / Ad group", "metrics.impressions", "metrics.clicks", "metrics.cost_micros", "metrics.ctr", "metrics.average_cpm", "metrics.conversions", "metrics.active_view_impressions"], true, "Metric names from metrics.proto v22; the report layout itself is a working shape")],
  meta: [RT("campaign", "Ads Manager export · campaign level", "One row per campaign and reporting window: impressions, reach, frequency, spend, clicks, results.", ["qa", "rf"], ["date_start / Reporting starts", "date_stop / Reporting ends", "campaign_name / Campaign name", "impressions", "reach", "frequency", "spend / Amount spent", "clicks / Clicks (all)", "cpm", "ctr / CTR (all)", "actions / Results"], true, "Level 'campaign' in the AdsInsights SDK enumeration; export labels are working names"), RT("adset", "Ads Manager export · ad set level", "One row per ad set: reach is recomputed per object and never sums to the campaign.", ["qa"], ["date_start / Reporting starts", "date_stop / Reporting ends", "campaign_name / Campaign name", "adset_name / Ad set name", "impressions", "reach", "frequency", "spend / Amount spent", "inline_link_clicks / Link clicks", "video_thruplay_watched_actions / ThruPlays"], true, "Level 'adset' in the AdsInsights SDK enumeration"), RT("ad", "Ads Manager export · ad level", "One row per ad (creative).", ["qa"], ["date_start / Reporting starts", "date_stop / Reporting ends", "adset_name / Ad set name", "ad_name / Ad name", "impressions", "reach", "spend / Amount spent", "video_play_actions", "video_p100_watched_actions"], true, "Level 'ad' in the AdsInsights SDK enumeration")],
  linkedin: [RT("campaign_performance", "Campaign performance export", "Campaign Manager analytics by campaign and day: impressions, clicks, spend, approximate member reach, video views, leads.", ["qa", "rf"], ["Start Date (in UTC)", "Campaign Group Name", "Campaign Name", "Impressions", "Clicks", "Total Spent", "Average CPM", "Click Through Rate", "Approximate Member Reach (approximateMemberReach)", "Video Views", "Video Completions", "Leads"], false, "Working shape; the ads-reporting page was not reachable from the build environment")],
  tiktok: [RT("campaign", "Campaign report", "Auction campaign delivery: cost, impressions, clicks, reach, frequency, video views.", ["qa"], ["stat_time_day / Date", "Campaign name", "Ad group name", "Cost", "Impressions", "Clicks", "CTR", "CPM", "Reach", "Frequency", "Video views", "Video views at 100%"], false, "Endpoint parameters verified (report_type, data_level, dimensions, metrics); metric names are working names")],
  reddit: [RT("campaign", "Campaign report", "Campaign, ad group and ad delivery with reach and video views.", ["qa"], ["Date", "Campaign", "Ad group", "Impressions", "Clicks", "CTR", "Spend", "CPM", "Reach", "Frequency", "Video views", "Video fully viewed"], false, "Working shape; the Ads API reference was not reachable")],
  comscore: [RT("campaign_ratings", "Campaign Ratings (CCR) export", "Person-level unique audience, % reach, frequency, exclusive and duplicated audience per media entity.", ["interpret", "rf"], ["Media / Entity / Placement", "Unique Audience (000)", "% Reach", "Frequency", "Exclusive Reach (000) / Exclusive Unique Audience", "Duplicated Audience (000)", "Total Digital Population (000)", "In-Target %", "Impressions"], false, "Working shape from the reach guide; no public field reference reachable")],
  datorama_table: [RT("table_export", "Table export (client QA contract)", "The Datorama Table widget export the four-tier QA reads: header in row 1, the required PMI columns, Table never Pivot.", ["qa"], ["Day", "Data Stream", "Media Buy Name", "PMI Media Buy Site Name", "PMI Buying Region", "PMI Funding Source", "PMI Cost Method", "PMI Plan Spend", "PMI Total Spend v2", "PMI Actualized Spend", "PMI Impressions", "PMI Month Status"], false, "The client brief as encoded in the Hub's QA; Datorama help was not reachable")],
  datorama_pivot: [RT("benchmark_pivot", "Benchmark pivot", "Channel × publisher × audience × format with the benchmark metrics.", ["benchmarks"], ["Channel", "Publisher", "Audience", "Format", "CTR · CPM · VCR · CPC (metric columns)"], false, "Working shape")],
  newsletter: [RT("send_report", "Publisher send report", "Per issue: sends, unique opens, opens, clicks.", ["qa", "rf"], ["Newsletter / Publication / Sponsor", "Issue date / Send date", "Sends / Delivered / List size", "Unique opens / Unique openers", "Opens", "Open rate", "Clicks / Unique clicks", "Unsubscribes"], false, "No vendor standard")],
  vendor: [RT("custom", "Vendor 1P report", "Whatever the partner sends; mapped once and remembered.", ["qa", "rf", "delivery"], ["Partner / Vendor / Placement / Line", "Date / Period / Month / Week", "Impressions / Trips / Plays / Units", "Reach / Unique / Households", "Cost / Spend"], false, "No vendor standard")],
};
const rtOf = (p, k) => (REPORT_TYPES[p] || []).find(t => t.key === k) || null;
const rtField = (p, name) => { const P = PLATFORM_DOCS[p]; if (!P) return null; const n = normH(name); return P.fields.find(f => normH(f.n) === n) || P.fields.find(f => f.n.split(" / ").some(a => normH(a) === n)) || null; };

// ---------- Active reports ----------
const AR_CADENCES = [["weekly", "Weekly"], ["monthly", "Monthly"], ["daily", "Daily (business days)"]];
const AR_WD = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const arClients = () => clientNames();
function arClient() { const names = arClients(); if (V.arClient && names.includes(V.arClient)) return V.arClient; const cn = currentClient(); V.arClient = cn && names.includes(cn) ? cn : names[0] || ""; return V.arClient; }
const arWs = cn => wsOfClient(cn);
function arRules(cn) { const ids = new Set(arWs(cn).map(c => c.id)); return live("rules").filter(r => ids.has(r.client_id)); }
function arDates(rule, start, end) { if (rule.active === false) return []; if (rule.cadence === "daily") { const out = []; for (let s = start; s <= end; s = addDays(s, 1)) if (isBday(s)) out.push(s); return out; } return cycles(rule, start, end).map(c => c.date); }
function arNext(rule) { const t = today(); return arDates(rule, t, addDays(t, 62))[0] || null; }
const arLabelDay = r => r.cadence === "weekly" ? AR_WD[r.weekday || 0] : r.cadence === "monthly" ? (r.business_day ? `business day ${r.business_day}` : `day ${r.day_of_month || 1} (prior business day)`) : "every business day";
function arForm(cn) { const f = V.arForm || (V.arForm = {name: "", cadence: "weekly", weekday: 0, day_of_month: 5, send_time: "09:00", timezone: "America/New_York", owner_id: ME()?.id || "", client_id: (V.ws && arWs(cn).some(c => c.id === V.ws) ? V.ws : arWs(cn)[0]?.id) || "", platform: "", report_type: "", recipients: "", notes: ""}); const rts = f.platform ? (REPORT_TYPES[f.platform] || []) : []; const users = live("users").filter(u => u.status !== "requested");
  return `<div class="card"><div class="topbar"><b>Add a report to ${esc(cn)}'s structure</b><span class="lab">name it and set its cadence — it lands in the weekly or monthly list and on the calendar, and its outreach → QA → send tasks are generated for the next three months</span></div><div class="arform"><label class="lab">Report name<br><input id="ar_name" ${inp} placeholder="Weekly pacing · Brand" value="${esc(f.name)}"></label><label class="lab">Cadence<br><select id="ar_cad" ${inp}>${AR_CADENCES.map(([k, n]) => `<option value="${k}" ${f.cadence === k ? "selected" : ""}>${n}</option>`).join("")}</select></label>${f.cadence === "weekly" ? `<label class="lab">Day<br><select id="ar_day" ${inp}>${AR_WD.slice(0, 5).map((d, i) => `<option value="${i}" ${+f.weekday === i ? "selected" : ""}>${d}</option>`).join("")}</select></label>` : f.cadence === "monthly" ? `<label class="lab">Day of month<br><select id="ar_day" ${inp}>${Array.from({length: 28}, (_, i) => i + 1).map(d => `<option value="${d}" ${+f.day_of_month === d ? "selected" : ""}>${d}</option>`).join("")}</select></label>` : ""}<label class="lab">Send time<br><input id="ar_time" ${inp} type="time" value="${esc(f.send_time)}"></label><label class="lab">Time zone<br><select id="ar_tz" ${inp}>${TZS.map(z => `<option ${f.timezone === z ? "selected" : ""}>${z}</option>`).join("")}</select></label><label class="lab">Owner<br><select id="ar_owner" ${inp}><option value="">…</option>${opt(users, f.owner_id, u => u.name || u.email)}</select></label><label class="lab">Line of business<br><select id="ar_ws" ${inp}>${arWs(cn).map(c => `<option value="${c.id}" ${f.client_id === c.id ? "selected" : ""}>${esc(c.lob || c.name)}</option>`).join("")}</select></label><label class="lab">Platform (optional)<br><select id="ar_plat" ${inp}><option value="">—</option>${Object.entries(PLATFORM_DOCS).map(([k, p]) => `<option value="${k}" ${f.platform === k ? "selected" : ""}>${esc(p.label)}</option>`).join("")}</select></label><label class="lab">Report type<br><select id="ar_rt" ${inp} ${rts.length ? "" : "disabled"}><option value="">—</option>${rts.map(t => `<option value="${t.key}" ${f.report_type === t.key ? "selected" : ""}>${esc(t.label)}</option>`).join("")}</select></label><label class="lab" style="grid-column:span 2">Recipients (comma)<br><input id="ar_rcpt" ${inp} placeholder="client@…, account lead" value="${esc(f.recipients)}"></label><label class="lab" style="grid-column:span 2">Notes<br><input id="ar_notes" ${inp} placeholder="what goes in it, where it comes from" value="${esc(f.notes)}"></label><div style="display:flex;align-items:flex-end"><button class="btn" data-ar="save">Add report</button></div></div></div>`; }
function arList(title, rules, dayLabel) { return `<div class="card"><div class="topbar"><b>${title}</b><span class="lab">${rules.length}</span></div><table><thead><tr><th>Report</th><th>${dayLabel}</th><th>Time</th><th>Owner</th><th>LOB</th><th>Platform · report</th><th>Next</th><th>Recipients</th><th></th></tr></thead><tbody>${rules.map(r => { const nx = arNext(r); const c = byId("clients", r.client_id); return `<tr class="${r.active === false ? "lab" : ""}"><td><b>${esc(r.name)}</b>${r.notes ? `<div class="lab">${esc(r.notes)}</div>` : ""}</td><td>${esc(arLabelDay(r))}</td><td class="mono">${esc(r.send_time || "09:00")} <span class="lab">${esc((r.timezone || "").split("/")[1] || r.timezone || "")}</span></td><td class="lab">${esc(byId("users", r.owner_id)?.name || "—")}</td><td class="lab">${esc(c?.lob || c?.name || "—")}</td><td class="lab">${r.platform ? esc(PLATFORM_DOCS[r.platform]?.label || r.platform) + (r.report_type ? " · " + esc(rtOf(r.platform, r.report_type)?.label || r.report_type) : "") : (r.inputs || []).map(esc).join(", ") || "—"}</td><td class="mono">${r.active === false ? pill("paused", "warn") : nx ? esc(nx) : "—"}</td><td class="lab" style="font-size:11.5px">${esc(r.recipients || "")}</td><td><button class="btn ghost xs" data-ar="toggle" data-v="${r.id}">${r.active === false ? "Resume" : "Pause"}</button> <button class="btn ghost xs" data-ar="trash" data-v="${r.id}" title="Trash the rule; its open tasks stay until done">Trash</button></td></tr>`; }).join("") || `<tr><td colspan="9" class="lab">None yet.</td></tr>`}</tbody></table></div>`; }
function arCalendar(cn, rules) { const view = V.arView || "month"; const anchor = V.arAnchor || today(); const y = +anchor.slice(0, 4), m = +anchor.slice(5, 7); const first = `${anchor.slice(0, 7)}-01`; const last = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10); const wkStart = addDays(anchor, -((dow(anchor) + 1) % 7)); const wkEnd = addDays(wkStart, 6); const [s, e] = view === "month" ? [first, last] : [wkStart, wkEnd]; const ev = {}; for (const r of rules) for (const d of arDates(r, s, e)) (ev[d] ||= []).push(r); const chip = r => `<span class="archip ${r.cadence}" title="${esc(r.name)} · ${esc(arLabelDay(r))} ${esc(r.send_time || "")}">${esc(r.name)}</span>`;
  const head = `<div class="topbar"><b>Calendar</b><div class="seg"><button class="${view === "month" ? "on" : ""}" data-ar="view" data-v="month">This month</button><button class="${view === "week" ? "on" : ""}" data-ar="view" data-v="week">This week</button></div><span class="spacer"></span><button class="btn ghost xs" data-ar="nav" data-v="-1">‹</button><b style="min-width:150px;text-align:center">${view === "month" ? new Date(first + "T00:00:00Z").toLocaleString("en-US", {month: "long", year: "numeric", timeZone: "UTC"}) : `${wkStart} – ${wkEnd}`}</b><button class="btn ghost xs" data-ar="nav" data-v="1">›</button><button class="btn ghost xs" data-ar="today">Today</button></div>`;
  if (view === "week") return `<div class="card">${head}<div class="arweek">${Array.from({length: 7}, (_, i) => addDays(wkStart, i)).map(d => `<div class="ard ${d === today() ? "today" : ""}"><div class="ah">${["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][(dow(d) + 1) % 7]} <span class="lab">${+d.slice(8)}</span></div>${(ev[d] || []).sort((a, b) => (a.send_time || "").localeCompare(b.send_time || "")).map(r => `<div class="are"><span class="mono lab">${esc(r.send_time || "")}</span> ${chip(r)}</div>`).join("") || `<div class="lab">—</div>`}</div>`).join("")}</div><div class="lab">${rules.filter(r => r.active !== false).length} active report(s) · times in each report's own time zone</div></div>`;
  const pad = (dow(first) + 1) % 7; const n = +last.slice(8); const cells = []; for (let i = 0; i < pad; i++) cells.push(`<div class="ard off"></div>`); for (let d = 1; d <= n; d++) { const key = `${anchor.slice(0, 7)}-${String(d).padStart(2, "0")}`; const rs = (ev[key] || []).sort((a, b) => (a.send_time || "").localeCompare(b.send_time || "")); cells.push(`<div class="ard ${key === today() ? "today" : ""} ${(dow(key) + 1) % 7 === 0 || (dow(key) + 1) % 7 === 6 ? "wknd" : ""}"><div class="ah">${d}</div>${rs.slice(0, 4).map(chip).join("")}${rs.length > 4 ? `<span class="lab">+${rs.length - 4}</span>` : ""}</div>`); }
  return `<div class="card">${head}<div class="armonth"><div class="ch">Sun</div><div class="ch">Mon</div><div class="ch">Tue</div><div class="ch">Wed</div><div class="ch">Thu</div><div class="ch">Fri</div><div class="ch">Sat</div>${cells.join("")}</div><div class="lab"><span class="archip weekly">weekly</span> <span class="archip monthly">monthly</span> <span class="archip daily">daily</span> · monthly reports fall on the prior business day when the day is a weekend · ${rules.filter(r => r.active !== false).length} active report(s)</div></div>`; }
function pActiveReports() { const names = arClients(); const cn = arClient(); if (!cn) return `<div class="empty"><b>No clients yet</b>Add a client and workspace in Settings first.</div>`; const rules = arRules(cn).sort((a, b) => a.name.localeCompare(b.name)); const weekly = rules.filter(r => r.cadence === "weekly"), monthly = rules.filter(r => r.cadence === "monthly"), daily = rules.filter(r => r.cadence === "daily");
  return `<div class="seg artabs">${names.map(n => `<button class="${n === cn ? "on" : ""}" data-ar="client" data-v="${esc(n)}">${esc(n)} <span class="cnt">${arRules(n).length}</span></button>`).join("")}</div>${arForm(cn)}<div class="argrid">${arList("Weekly reports", weekly, "Day")}${arList("Monthly reports", monthly, "Day of month")}</div>${daily.length ? arList("Daily reports", daily, "Days") : ""}${arCalendar(cn, rules)}`; }
function arReadForm() { const f = V.arForm || {}; f.name = val("ar_name"); f.cadence = val("ar_cad") || f.cadence || "weekly"; if (f.cadence === "weekly") f.weekday = +val("ar_day") || 0; else if (f.cadence === "monthly") f.day_of_month = +val("ar_day") || 1; f.send_time = val("ar_time") || "09:00"; f.timezone = val("ar_tz") || "America/New_York"; f.owner_id = val("ar_owner"); f.client_id = val("ar_ws"); f.platform = val("ar_plat"); f.report_type = val("ar_rt"); f.recipients = val("ar_rcpt"); f.notes = val("ar_notes"); V.arForm = f; return f; }
document.addEventListener("click", async e => { const b = e.target.closest("[data-ar]"); if (!b) return; const a = b.dataset.ar, v = b.dataset.v; try {
  if (a === "client") { V.arClient = v; V.arForm = null; }
  else if (a === "view") V.arView = v; else if (a === "today") V.arAnchor = today(); else if (a === "nav") { const view = V.arView || "month"; const an = V.arAnchor || today(); if (view === "week") V.arAnchor = addDays(an, 7 * +v); else { const d = new Date(an.slice(0, 7) + "-01T00:00:00Z"); d.setUTCMonth(d.getUTCMonth() + +v); V.arAnchor = d.toISOString().slice(0, 10); } }
  else if (a === "save") { const f = arReadForm(); if (!f.name.trim()) return toast("Give the report a name."); if (!f.client_id) return toast("Choose the line of business."); const owner = f.owner_id || ME()?.id || ""; if (live("rules").some(r => norm(r.name) === norm(f.name) && (r.client_id || null) === f.client_id)) return toast("A report with that name already exists for that line of business."); const rule = {name: f.name.trim(), owner_id: owner, cadence: f.cadence, timezone: f.timezone, send_time: f.send_time, inputs: f.platform ? [PLATFORM_DOCS[f.platform]?.label || f.platform] : [], effort: 2, outreach_days_before: 2, campaign_id: null, client_id: f.client_id, kind: "client_report", platform: f.platform || null, report_type: f.report_type || null, recipients: f.recipients || "", notes: f.notes || "", active: true}; if (f.cadence === "weekly") rule.weekday = f.weekday; else if (f.cadence === "monthly") rule.day_of_month = f.day_of_month; const r = await put("rules", rule); let made = 0; if (rule.cadence !== "daily" && owner) { for (const it of instances(r, today(), addDays(today(), 92))) { const bk = it.blocked_by_kind; delete it.blocked_by_kind; const blocked = bk ? live("tasks").find(t => t.rule_id === r.id && t.cycle === it.cycle && t.kind === bk) : null; await put("tasks", {...it, assignee_id: owner, rule_id: r.id, timezone: r.timezone, blocked_by_id: blocked?.id || null, status: blocked ? "blocked" : "open", reminder_at: it.due_at, reminded_at: null}); made++; } } V.arForm = null; toast(`${r.name} added${made ? ` · ${made} tasks generated for the next 3 months` : rule.cadence === "daily" ? " · daily reports are listed and calendared; no tasks are generated per day" : " · no owner, so no tasks were generated"}`); }
  else if (a === "toggle") { const r = byId("rules", v); if (!r) return; const before = {...r}; r.active = r.active === false; await put("rules", r, "update", before); }
  else if (a === "trash") { if (!confirm("Trash this report rule? Its open tasks stay until done.")) return; await trash("rules", v); }
  else return; render(); } catch (err) { console.error(err); toast("Error: " + (err.message || err)); } });
document.addEventListener("change", e => { const t = e.target; if (!t.id || !t.id.startsWith("ar_")) return; if (t.id === "ar_cad" || t.id === "ar_plat") { arReadForm(); if (t.id === "ar_plat") V.arForm.report_type = ""; render(); } });

// ---------- QA / Interpret landing: platform → report type → upload | old reports → field map ----------
const RL_INTENT = {qa: {title: "QA a report", sub: "pick the platform, then the report you are checking; drop the export and the four-tier or starter QA runs"}, interpret: {title: "Interpret a report", sub: "pick the platform, then the reach report; drop the export and the overlap guide reads it"}};
function rlState(intent) { return ((V.rl ||= {})[intent] ||= {platform: null, rt: null, open: null}); }
const rlTemplates = (intent, p) => live("upload_templates").filter(t => t.intent === intent && t.platform === p && (t.share_all || !V.ws || wizSame(t.client_id, V.ws)));
function rlPlatforms(intent) { return Object.entries(PLATFORM_DOCS).filter(([k]) => (REPORT_TYPES[k] || []).some(t => t.intents.includes(intent)) || rlTemplates(intent, k).length); }
function rlOld(intent, p, rt) { const lab = PLATFORM_DOCS[p]?.label; const legacy = Object.entries(WIZ_LEGACY).filter(([, k]) => k === p).map(([l]) => l); const ups = live("uploads").filter(u => u.intent === intent && u.platform === p && (!V.ws || !u.client_id || wizSame(u.client_id, V.ws)) && (!rt || !u.report_type || u.report_type === rt)).map(u => ({kind: "upload", id: u.id, name: u.filename, when: u.wiz?.processed_at || u.updated_at || "", summary: u.wiz?.summary || ""})); const reps = intent === "interpret" ? live("reports").filter(r => r.kind === "interpretation" && inWs(r) && (r.body?.platform === lab || legacy.includes(r.body?.platform))).map(r => ({kind: "report", id: r.id, name: r.name, when: r.created_at || "", summary: `${(r.body?.findings || []).length} finding(s)${r.meta?.window ? " · " + r.meta.window : ""}`})) : []; const runs = intent === "qa" && p === "datorama_table" ? live("qa_runs").filter(r => !V.ws || sameWs(r.client_id, V.ws)).map(r => ({kind: "run", id: r.id, name: r.file, when: r.ts, summary: `${r.status} · ${r.rows_n} rows`})) : []; return [...reps, ...ups, ...runs].sort((a, b) => (b.when || "").localeCompare(a.when || "")).slice(0, 12); }
function rlOpenHtml(intent, L) { if (!L.open) return ""; const [kind, id] = L.open.split(":"); if (kind === "report") { const r = byId("reports", id); return r ? `<div class="card"><div class="topbar"><b>${esc(r.name)}</b><span class="lab">${(r.created_at || "").slice(0, 16).replace("T", " ")}</span><span class="spacer"></span><button class="btn ghost xs" data-rl="close">Close</button></div>${repView(r)}</div>` : ""; } if (kind === "upload") { const u = byId("uploads", id); const R = u?.wiz?.result; return u ? `<div class="card"><div class="topbar"><b>${esc(u.filename)}</b><span class="lab">${esc(u.wiz?.summary || "")}</span><span class="spacer"></span><button class="btn ghost xs" data-rl="close">Close</button></div>${R?.findings ? findings(R.findings.map(f => ({...f, rows: [], name: f.rule, source: ""}))) : R?.run_id ? `<a class="btn ghost sm" href="#datorama" data-w="goto_qa" data-v="${R.run_id}">Open the QA run</a>` : `<div class="lab">${esc(JSON.stringify(R || {}).slice(0, 600))}</div>`}</div>` : ""; } if (kind === "run") { const r = byId("qa_runs", id); return r ? `<div class="card"><div class="topbar"><b>${esc(r.file)}</b>${pill(r.status, r.status === "PASSED" ? "ok" : r.status === "BLOCKED" ? "bad" : "warn")}<span class="lab">${r.ts.slice(0, 16).replace("T", " ")} · ${r.rows_n} rows</span><span class="spacer"></span><a class="btn ghost xs" href="#datorama" data-w="goto_qa" data-v="${r.id}">Open in Datorama › QA</a><button class="btn ghost xs" data-rl="close">Close</button></div><div class="lab">${(r.flags || []).filter(f => !f.ok).slice(0, 8).map(f => `<div>${esc(f.code)} — ${esc(f.test || f.fix || "")}</div>`).join("") || "No open flags."}</div></div>` : ""; } return ""; }
function rlFieldMap(intent, L, W) { const p = L.platform; const P = PLATFORM_DOCS[p]; if (!P) return ""; const tpl = L.rt && L.rt.startsWith("tpl:") ? byId("upload_templates", L.rt.slice(4)) : null; const rt = tpl ? null : rtOf(p, L.rt); const rows = tpl ? Object.entries(tpl.mapping).map(([src, hub]) => ({n: src, hub, note: "saved mapping", v: null})) : (rt?.fields || []).map(n => { const f = rtField(p, n); return {n, hub: f?.hub || null, note: f?.note || "", v: f ? f.v : null, kind: f?.k || ""}; }); const has = n => W?.headers ? W.headers.some(h => normH(h) === normH(n) || n.split(" / ").some(a => normH(a.replace(/\(.*?\)/g, "").trim()) === normH(h))) : null;
  return `<div class="card"><div class="topbar"><b>Field map · ${esc(tpl ? tpl.name : rt?.label || "")}</b><span class="lab">${tpl ? `template v${tpl.version || 1} · ${Object.keys(tpl.mapping).length} columns mapped` : `${esc(rt?.src || "")}`}</span><span class="spacer"></span>${rt ? (rt.v ? pill("report type verified " + WIZ_CHECKED, "ok") : pill("report type unverified", "warn")) : ""}</div><table><thead><tr><th>Export column</th><th>Hub field</th><th>Meaning · how to read it</th><th>Name verified</th>${W?.headers ? "<th>In this file</th>" : ""}</tr></thead><tbody>${rows.map(r => `<tr><td class="mono" style="font-size:11.5px">${esc(r.n)}</td><td>${r.hub ? esc(HUB_T[r.hub]?.label || r.hub) : `<span class="lab">— (not mapped)</span>`}</td><td style="font-size:12px">${esc(r.note || HUB_T[r.hub]?.desc || "")}</td><td>${r.v === true ? pill("yes", "ok") : r.v === false ? pill("working name", "dim") : `<span class="lab">—</span>`}</td>${W?.headers ? `<td>${has(r.n) ? pill("yes", "ok") : pill("no", "dim")}</td>` : ""}</tr>`).join("")}</tbody></table><div class="lab">Documentation: ${P.docs.map(d => d.u ? `<a href="${esc(d.u)}" target="_blank" rel="noopener">${esc(d.t)}</a> ${d.v ? "(verified " + WIZ_CHECKED + ")" : "(not reachable from the build environment)"}` : esc(d.t)).join(" · ")}</div></div>`; }
function pReportLanding(intent) { const L = rlState(intent); const I = RL_INTENT[intent]; const W = V.wiz && V.wiz.host === "landing:" + intent ? V.wiz : null; const plats = rlPlatforms(intent);
  const crumbs = `<div class="rlcrumb"><a data-rl="plat" data-v="">${esc(I.title)}</a>${L.platform ? ` › <a data-rl="rt" data-v="">${esc(PLATFORM_DOCS[L.platform]?.label || L.platform)}</a>` : ""}${L.rt ? ` › <b>${esc(L.rt.startsWith("tpl:") ? byId("upload_templates", L.rt.slice(4))?.name || "template" : rtOf(L.platform, L.rt)?.label || L.rt)}</b>` : ""}</div>`;
  if (!L.platform) return `<div class="card"><div class="topbar"><b>${esc(I.title)}</b><span class="lab">${esc(I.sub)}</span></div>${crumbs}<div class="optcards rlplat">${plats.map(([k, p]) => { const n = (REPORT_TYPES[k] || []).filter(t => t.intents.includes(intent)).length; const tn = rlTemplates(intent, k).length; return `<div class="optcard" data-rl="plat" data-v="${k}"><div class="t">${esc(p.label)}</div><div class="d">${esc(p.family)} · ${n} report type${n === 1 ? "" : "s"}${tn ? ` · ${tn} saved template${tn === 1 ? "" : "s"}` : ""}</div><div class="f">${p.docs.some(d => d.v) ? "verified source" : "unverified — check the link"}</div></div>`; }).join("")}</div></div>`;
  const P = PLATFORM_DOCS[L.platform]; const rts = (REPORT_TYPES[L.platform] || []).filter(t => t.intents.includes(intent)); const tpls = rlTemplates(intent, L.platform);
  if (!L.rt) return `<div class="card"><div class="topbar"><b>${esc(P.label)} · which report?</b><span class="lab">the report types templatized for ${esc(I.title.toLowerCase())}, plus mappings saved for this client</span></div>${crumbs}<div class="optcards rlplat">${rts.map(t => `<div class="optcard" data-rl="rt" data-v="${t.key}"><div class="t">${esc(t.label)}${t.v ? "" : qi("Report type not verified against a reachable official source; column names are working names.")}</div><div class="d">${esc(t.desc)}</div><div class="f">${t.fields.length} columns · ${esc(t.src)}</div></div>`).join("")}${tpls.map(t => `<div class="optcard tpl" data-rl="rt" data-v="tpl:${t.id}"><div class="t">${esc(t.name)} <span class="lab">v${t.version || 1}</span></div><div class="d">Saved mapping · ${Object.keys(t.mapping).length} columns · ${t.share_all ? "every client" : esc(byId("clients", t.client_id) ? wsName(byId("clients", t.client_id)) : "this client")}</div><div class="f">runs without a mapping step</div></div>`).join("")}${!rts.length && !tpls.length ? `<div class="lab">Nothing templatized for this platform yet — drop a file in Data streams to create the first template.</div>` : ""}</div></div>`;
  const tpl = L.rt.startsWith("tpl:") ? byId("upload_templates", L.rt.slice(4)) : null; const rt = tpl ? null : rtOf(L.platform, L.rt); const old = rlOld(intent, L.platform, tpl ? null : L.rt); const busy = W && W.stage >= 3;
  const duo = `<div class="rlduo"><div class="card"><div class="topbar"><b>Upload a report</b><span class="lab">${esc(tpl ? tpl.name : rt?.label || "")}</span></div>${dropzone("rl_file_" + intent, "Drop the export here", `CSV or .xlsx (first sheet) · recognised against ${esc(P.label)} and this client's templates, then ${intent === "qa" ? "QA runs" : "the overlap guide reads it"}`, {hero: !busy})}<input type="file" id="rl_file_${intent}" accept=".csv,.txt,.tsv,.xlsx,.xls" hidden><div class="lab">Plan, window and divisor settings appear in the Map stage once the file is recognised.</div></div><div class="card"><div class="topbar"><b>View old reports</b><span class="lab">${old.length} for ${esc(P.label)}</span></div>${old.length ? `<table><thead><tr><th>Report</th><th>When</th><th>Result</th><th></th></tr></thead><tbody>${old.map(o => `<tr class="${L.open === o.kind + ":" + o.id ? "sel" : ""}"><td><b>${esc(o.name)}</b> <span class="lab">${o.kind === "report" ? "interpretation" : o.kind === "run" ? "QA run" : "upload"}</span></td><td class="lab">${esc(String(o.when).slice(0, 16).replace("T", " "))}</td><td style="font-size:12px">${esc(o.summary)}</td><td><button class="btn ghost xs" data-rl="open" data-v="${o.kind}:${o.id}">Open</button></td></tr>`).join("")}</tbody></table>` : `<div class="empty"><b>Nothing yet</b>${intent === "qa" ? "QA results" : "Interpretations"} for this platform will list here.</div>`}</div></div>`;
  const wiz = busy ? `<div class="dstream">${wizStagesHtml(W)}${wizWindowHtml(W)}</div>` : "";
  return `<div class="card"><div class="topbar"><b>${esc(I.title)} · ${esc(P.label)}</b><span class="lab">${esc(tpl ? "saved template" : rt?.desc || "")}</span></div>${crumbs}</div>${duo}${wiz}${rlOpenHtml(intent, L)}${rlFieldMap(intent, L, W)}`; }
document.addEventListener("click", e => { const b = e.target.closest("[data-rl]"); if (!b) return; const tab = V.repTab; const intent = tab === "qa" || tab === "interpret" ? tab : null; if (!intent) return; const L = rlState(intent); const a = b.dataset.rl, v = b.dataset.v; if (a === "plat") { L.platform = v || null; L.rt = null; L.open = null; } else if (a === "rt") { L.rt = v || null; L.open = null; } else if (a === "open") L.open = v; else if (a === "close") L.open = null; else return; render(); });
document.addEventListener("change", async e => { const t = e.target; const m = /^rl_file_(qa|interpret)$/.exec(t.id || ""); if (!m) return; const intent = m[1]; const f = t.files[0]; if (!f) return; const L = rlState(intent); try { wizReset(intent); const W = V.wiz; W.host = "landing:" + intent; W.presetPlatform = L.platform && L.platform !== "custom" ? L.platform : null; W.reportType = L.rt && !L.rt.startsWith("tpl:") ? L.rt : null; W.client_id = V.ws || W.client_id; await wizLoadFile(f); } catch (err) { console.error(err); toast("Error: " + (err.message || err)); } });
