
// ===== Create user v2 — one wide, horizontal form: Email · First name · Last name · Role · Client · Lines of business (all or some) · welcome email preview =====
function nuState() { return V.nu || (V.nu = {email: "", first: "", last: "", role: "viewer", client: "", lobs: "all"}); }
const nuLobs = cn => cn ? wsOfClient(cn) : [];
function nuWorkspaces(s) { if (!s.client) return "all"; const L = nuLobs(s.client); if (s.lobs === "all") return L.map(c => c.id); return (Array.isArray(s.lobs) ? s.lobs : []).filter(id => L.some(c => c.id === id)); }
function nuPreview(s) { const name = [s.first, s.last].map(x => String(x || "").trim()).filter(Boolean).join(" "); return welcomeEmail({name, role: s.role || "viewer", invite_token: "(minted when you click Create)"}); }
function nuLobsHtml(s) { const L = nuLobs(s.client); if (!s.client) return `<span class="lab">Choose a client to pick its lines of business, or leave “All clients” for a cross-client role.</span>`; if (!L.length) return `<span class="lab">This client has no workspaces yet.</span>`; const all = s.lobs === "all"; return `<label class="chk"><input type="checkbox" data-nu="lob_all" ${all ? "checked" : ""}> <b>All lines of business</b></label>${L.map(c => `<label class="chk"><input type="checkbox" data-nu="lob" value="${c.id}" ${all || (Array.isArray(s.lobs) && s.lobs.includes(c.id)) ? "checked" : ""} ${all ? "disabled" : ""}> ${esc(c.lob || c.name)}</label>`).join("")}`; }
function nuFormHtml(s) { const clients = clientNames(); return `<div class="nuform"><div class="row4"><div class="fld"><label>Email</label><input class="inp" data-nu="email" type="email" placeholder="name@omc.com" value="${esc(s.email)}" autocomplete="off"></div><div class="fld"><label>First name</label><input class="inp" data-nu="first" value="${esc(s.first)}"></div><div class="fld"><label>Last name</label><input class="inp" data-nu="last" value="${esc(s.last)}"></div><div class="fld"><label>Role</label><select class="inp" data-nu="role">${["admin", "editor", "viewer"].map(r => `<option value="${r}" ${s.role === r ? "selected" : ""}>${r}</option>`).join("")}</select><span class="hint">admins hold every capability</span></div></div><div class="row2"><div class="fld"><label>Client</label><select class="inp" data-nu="client"><option value="">All clients (cross-client role)</option>${clients.map(c => `<option value="${esc(c)}" ${s.client === c ? "selected" : ""}>${esc(c)}</option>`).join("")}</select><span class="hint">the workspaces the person can open</span></div><div class="fld"><label>Lines of business</label><div class="nulobs" id="nu_lobs">${nuLobsHtml(s)}</div></div></div><div class="fld"><label>Welcome email preview</label><textarea class="inp" id="nu_preview" rows="9" readonly>${esc(nuPreview(s))}</textarea><span class="hint">updates as you type; after Create, open it in your mail client from the user's Invitation card — the invite code is minted on save</span></div></div>`; }
function openUserDrawer() { const s = nuState(); openDrawer({crumb: ["Users", "Create user"], title: "Create user", sub: "an invite code is minted; the person links their account on first open", fields: [], extra: nuFormHtml(s), saveLabel: "Create and invite", validate: () => { const st = nuState(); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(st.email || "").trim())) return "Enter a valid work email"; if (!String(st.first || "").trim()) return "First name is required"; if (st.client && !nuWorkspaces(st).length) return "Pick at least one line of business, or All"; return null; }, onSave: async () => { const st = nuState(); const ws = nuWorkspaces(st); const u = await inviteUser({email: st.email.trim(), name: [st.first.trim(), st.last.trim()].filter(Boolean).join(" "), role: st.role, team: "", workspaces: ws === "all" ? "all" : ws}); if (u) { const before = {...u}; u.first_name = st.first.trim(); u.last_name = st.last.trim(); u.client = st.client || null; await put("users", u, "update", before); V.userOpen = u.id; } V.nu = null; }}); document.getElementById("drawer")?.classList.add("wide"); }
document.addEventListener("click", e => { const b = e.target.closest('[data-dr="user_new"]'); if (!b) return; if (b.disabled) return; openUserDrawer(); });
document.addEventListener("input", e => { const t = e.target; if (!t.dataset?.nu || !t.closest("#drawer")) return; const s = nuState(); const k = t.dataset.nu; if (["email", "first", "last"].includes(k)) { s[k] = t.value; const pv = document.getElementById("nu_preview"); if (pv) pv.value = nuPreview(s); } });
document.addEventListener("change", e => { const t = e.target; if (!t.dataset?.nu || !t.closest("#drawer")) return; const s = nuState(); const k = t.dataset.nu; if (k === "role") { s.role = t.value; const pv = document.getElementById("nu_preview"); if (pv) pv.value = nuPreview(s); } else if (k === "client") { s.client = t.value; s.lobs = "all"; const box = document.getElementById("nu_lobs"); if (box) box.innerHTML = nuLobsHtml(s); } else if (k === "lob_all") { s.lobs = t.checked ? "all" : []; const box = document.getElementById("nu_lobs"); if (box) box.innerHTML = nuLobsHtml(s); } else if (k === "lob") { const arr = Array.isArray(s.lobs) ? s.lobs.slice() : []; if (t.checked) { if (!arr.includes(t.value)) arr.push(t.value); } else { const i = arr.indexOf(t.value); if (i >= 0) arr.splice(i, 1); } s.lobs = arr; } else if (["email", "first", "last"].includes(k)) { s[k] = t.value; } });
