/* Analytics Hub · self-hosted adapter
   Replaces the claude.ai runtime (window.claude.use) with Supabase Auth + Postgres so the
   unchanged page runs on any static host. Loaded BEFORE the page script by build.py.
   Requires window.HUB_CONFIG = {SUPABASE_URL, SUPABASE_ANON_KEY, ACCOUNT_NAME}. */
(function () {
  const CFG = window.HUB_CONFIG || {};
  const POLICY = {min: 10, rotateDays: 180};
  if (!window.supabase) { document.addEventListener("DOMContentLoaded", () => { const d = document.createElement("div"); d.id = "hub-auth"; d.innerHTML = '<div class="c"><h1>Sign-in service unavailable</h1><p>supabase-js did not load from cdn.jsdelivr.net. Check the network policy or host the file next to index.html.</p></div>'; document.body.appendChild(d); }); window.claude = {use: async () => null}; return; }
  const sb = window.supabase.createClient(CFG.SUPABASE_URL, CFG.SUPABASE_ANON_KEY, {auth: {persistSession: true, autoRefreshToken: true, detectSessionInUrl: true}});
  let session = null, profile = null, resolveAuth; const authReady = new Promise(r => resolveAuth = r);
  const $ = s => document.querySelector(s);
  const policyCheck = pw => ({length: pw.length >= POLICY.min, letters: /[A-Za-z]/.test(pw), numbers: /\d/.test(pw), special: /[^A-Za-z0-9\s]/.test(pw)});
  const policyOk = pw => Object.values(policyCheck(pw)).every(Boolean);
  const css = `#hub-auth{position:fixed;inset:0;z-index:1000;background:radial-gradient(1200px 600px at 20% -10%,rgba(226,143,85,.14),transparent 60%),#141110;display:grid;place-items:center;font-family:Inter,system-ui,sans-serif;color:#F3ECE4;padding:24px}#hub-auth .c{width:min(520px,100%);background:#1C1816;border:1px solid #3E3631;border-radius:16px;padding:34px 38px 26px;box-shadow:0 10px 30px rgba(0,0,0,.4);display:grid;gap:14px}#hub-auth .b{display:flex;gap:12px;align-items:center}#hub-auth .b i{width:34px;height:34px;border-radius:9px;background:linear-gradient(135deg,#E28F55,#F2C37B)}#hub-auth h1{margin:6px 0 0;font-size:26px;letter-spacing:-.02em}#hub-auth p{margin:0;color:#A0938A;font-size:13.5px;line-height:1.5}#hub-auth label{display:grid;gap:5px;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#A0938A;font-weight:600}#hub-auth input{height:40px;border-radius:9px;border:1px solid #4B423C;background:#241F1B;color:#F3ECE4;font:inherit;font-size:14px;padding:0 12px}#hub-auth input:focus{outline:none;border-color:#E28F55;box-shadow:0 0 0 3px rgba(226,143,85,.18)}#hub-auth button{height:42px;border:0;border-radius:9px;background:#E28F55;color:#1A120C;font:inherit;font-size:15px;font-weight:600;cursor:pointer}#hub-auth button.g{background:transparent;color:#D9CDC1;border:1px solid #4B423C}#hub-auth .r{display:flex;gap:10px;justify-content:space-between;align-items:center;font-size:13px;color:#A0938A}#hub-auth a{color:#F2C37B;cursor:pointer;text-decoration:none}#hub-auth .err{background:rgba(240,122,106,.15);border:1px solid rgba(240,122,106,.4);color:#F07A6A;padding:10px 12px;border-radius:9px;font-size:13px}#hub-auth .ok{background:rgba(127,203,154,.14);border:1px solid rgba(127,203,154,.4);color:#7FCB9A;padding:10px 12px;border-radius:9px;font-size:13px}#hub-auth ul.pol{margin:0;padding-left:18px;font-size:12.5px;color:#A0938A;display:grid;gap:3px}#hub-auth ul.pol li.y{color:#7FCB9A}#hub-auth .f{border-top:1px solid #3E3631;padding-top:12px;font-size:12px;color:#A0938A}`;
  function shell(inner) { let host = $("#hub-auth"); if (!host) { host = document.createElement("div"); host.id = "hub-auth"; const st = document.createElement("style"); st.textContent = css; document.head.appendChild(st); document.body.appendChild(host); } host.innerHTML = `<div class="c"><div class="b"><i></i><div><b>Analytics Hub</b><div style="font-size:12px;color:#A0938A">${CFG.ACCOUNT_NAME || ""}</div></div></div>${inner}<div class="f">Passwords: at least ${POLICY.min} characters, letters and numbers, one special character; changed every ${POLICY.rotateDays} days. Every action is written to the activity log.</div></div>`; host.style.display = "grid"; }
  function hide() { const h = $("#hub-auth"); if (h) h.style.display = "none"; }
  const polList = pw => { const c = policyCheck(pw); return `<ul class="pol"><li class="${c.length ? "y" : ""}">${POLICY.min}+ characters</li><li class="${c.letters && c.numbers ? "y" : ""}">letters and numbers</li><li class="${c.special ? "y" : ""}">one special character</li></ul>`; };
  function viewSignIn(msg) { shell(`<h1>Sign in</h1><p>Use the email and password you registered with. New here? <a data-v="register">Create an account</a>.</p>${msg || ""}<label>Email<input id="a_email" type="email" autocomplete="username"></label><label>Password<input id="a_pw" type="password" autocomplete="current-password"></label><button id="a_go">Sign in</button><div class="r"><a data-v="forgot">Forgot password?</a><a data-v="register">Create an account</a></div>`); $("#a_go").onclick = async () => { const {error} = await sb.auth.signInWithPassword({email: $("#a_email").value.trim(), password: $("#a_pw").value}); if (error) return viewSignIn(`<div class="err">${error.message}</div>`); }; }
  function viewRegister(msg) { shell(`<h1>Create your account</h1><p>Register once; an admin approves your profile and assigns your role and workspaces. You can come back any time.</p>${msg || ""}<label>Name<input id="a_name" autocomplete="name"></label><label>Work email<input id="a_email" type="email" autocomplete="username"></label><label>Password<input id="a_pw" type="password" autocomplete="new-password"></label><div id="a_pol">${polList("")}</div><button id="a_go">Create account</button><div class="r"><a data-v="signin">Back to sign in</a></div>`); $("#a_pw").oninput = () => $("#a_pol").innerHTML = polList($("#a_pw").value); $("#a_go").onclick = async () => { const pw = $("#a_pw").value; if (!policyOk(pw)) return viewRegister(`<div class="err">The password does not meet the policy.</div>`); const {error} = await sb.auth.signUp({email: $("#a_email").value.trim(), password: pw, options: {data: {name: $("#a_name").value.trim()}, emailRedirectTo: location.origin + location.pathname}}); if (error) return viewRegister(`<div class="err">${error.message}</div>`); viewSignIn(`<div class="ok">Account created. Check your email to confirm it, then sign in.</div>`); }; }
  function viewForgot(msg) { shell(`<h1>Reset password</h1><p>We email a reset link; it opens this page so you can set a new password.</p>${msg || ""}<label>Email<input id="a_email" type="email"></label><button id="a_go">Send reset link</button><div class="r"><a data-v="signin">Back to sign in</a></div>`); $("#a_go").onclick = async () => { const {error} = await sb.auth.resetPasswordForEmail($("#a_email").value.trim(), {redirectTo: location.origin + location.pathname}); viewForgot(error ? `<div class="err">${error.message}</div>` : `<div class="ok">If that address has an account, a reset link is on its way.</div>`); }; }
  function viewNewPassword(reason) { shell(`<h1>Set a new password</h1><p>${reason}</p><label>New password<input id="a_pw" type="password" autocomplete="new-password"></label><div id="a_pol">${polList("")}</div><button id="a_go">Save password</button>`); $("#a_pw").oninput = () => $("#a_pol").innerHTML = polList($("#a_pw").value); $("#a_go").onclick = async () => { const pw = $("#a_pw").value; if (!policyOk(pw)) return viewNewPassword("The password does not meet the policy."); const {error} = await sb.auth.updateUser({password: pw}); if (error) return viewNewPassword(error.message); await sb.from("profiles").update({password_changed_at: new Date().toISOString()}).eq("id", session.user.id); await start(true); }; }
  document.addEventListener("click", e => { const a = e.target.closest("#hub-auth [data-v]"); if (!a) return; ({signin: viewSignIn, register: viewRegister, forgot: viewForgot})[a.dataset.v](); });
  async function loadProfile() { const {data} = await sb.from("profiles").select("*").eq("id", session.user.id).maybeSingle(); profile = data; }
  async function start(afterPw) { const {data} = await sb.auth.getSession(); session = data.session; if (!session) return viewSignIn(); await loadProfile(); if (!afterPw && profile?.password_changed_at && (Date.now() - new Date(profile.password_changed_at)) / 86400000 > POLICY.rotateDays) return viewNewPassword(`Your password is older than ${POLICY.rotateDays} days. Choose a new one to continue.`); hide(); resolveAuth(); }
  sb.auth.onAuthStateChange((ev) => { if (ev === "PASSWORD_RECOVERY") { sb.auth.getSession().then(({data}) => { session = data.session; viewNewPassword("Choose a new password for your account."); }); } else if (ev === "SIGNED_IN" && !session) start(); else if (ev === "SIGNED_OUT") { session = null; profile = null; location.reload(); } });
  const err = (code, message) => { const e = new Error(message || code); e.code = code; return e; };
  const dbNs = Object.freeze({
    doc: path => { const [collection, ...rest] = path.split("/"); const id = rest.join("/"); return Object.freeze({
      set: async obj => { const {error} = await sb.from("docs").upsert({collection, id, data: obj, updated_at: new Date().toISOString()}); if (error) throw err(error.code === "42501" ? "permission_denied" : "invalid_argument", error.message); },
      get: async () => { const {data, error} = await sb.from("docs").select("data").eq("collection", collection).eq("id", id).maybeSingle(); if (error) throw err("invalid_argument", error.message); return {exists: !!data, id, data: () => data?.data}; },
      delete: async () => { const {error} = await sb.from("docs").delete().eq("collection", collection).eq("id", id); if (error) throw err("permission_denied", error.message); }}); },
    collection: name => Object.freeze({get: async () => { const out = []; let from = 0; for (;;) { const {data, error} = await sb.from("docs").select("id,data").eq("collection", name).range(from, from + 999); if (error) throw err("invalid_argument", error.message); out.push(...data); if (data.length < 1000) break; from += 1000; } return {docs: out.map(r => ({id: r.id, data: () => r.data}))}; }})
  });
  const userNs = Object.freeze({id: async () => session.user.id, me: async () => ({id: session.user.id, name: profile?.name || session.user.user_metadata?.name || "", email: session.user.email}), self: async () => ({id: session.user.id, name: profile?.name || session.user.user_metadata?.name || "", email: session.user.email}), isOwner: async () => !!(profile && profile.role === "admin" && profile.status === "active"), canEdit: async () => true, can: async () => true, profiles: async ids => Object.fromEntries(ids.map(i => [i, {id: i, name: ""}]))});
  window.claude = {use: async name => { if (name === "db") { await authReady; return dbNs; } if (name === "user") { await authReady; return userNs; } return null; }};
  window.HOSTED = {name: "supabase", resetPassword: email => sb.auth.resetPasswordForEmail(email, {redirectTo: location.origin + location.pathname}), signOut: () => sb.auth.signOut(), policy: POLICY, profile: () => profile, session: () => session};
  start();
})();
