/* Analytics Hub · self-hosted adapter
   Replaces the claude.ai runtime (window.claude.use) with Supabase Auth + Postgres so the unchanged page
   runs on any static host. build.py loads it in <head> after ./vendor/supabase.js and the deployment config.
   Requires window.HUB_CONFIG = {SUPABASE_URL, SUPABASE_ANON_KEY, ACCOUNT_NAME}.
   Storage mapping: the page's "users" collection is the profiles table (role and status live there and drive
   row-level security); every other collection is a row in docs (collection, id, data). */
(function () {
  const CFG = window.HUB_CONFIG || {};
  const POLICY = {min: 10, rotateDays: 180};
  const $ = s => document.querySelector(s);
  const esc = s => String(s == null ? "" : s).replace(/[&<>"']/g, c => ({"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"}[c]));
  const domReady = new Promise(r => document.readyState === "loading" ? document.addEventListener("DOMContentLoaded", () => r()) : r());
  const css = `#hub-auth{position:fixed;inset:0;z-index:100000;background:radial-gradient(1200px 600px at 20% -10%,rgba(226,143,85,.14),transparent 60%),#141110;display:grid;place-items:center;font-family:Inter,system-ui,sans-serif;color:#F3ECE4;padding:24px;overflow:auto}#hub-auth .c{width:min(520px,100%);background:#1C1816;border:1px solid #3E3631;border-radius:16px;padding:34px 38px 26px;box-shadow:0 10px 30px rgba(0,0,0,.4);display:grid;gap:14px}#hub-auth .b{display:flex;gap:12px;align-items:center}#hub-auth .b i{width:34px;height:34px;border-radius:9px;background:linear-gradient(135deg,#E28F55,#F2C37B)}#hub-auth h1{margin:6px 0 0;font-size:26px;letter-spacing:-.02em}#hub-auth p{margin:0;color:#A0938A;font-size:13.5px;line-height:1.5}#hub-auth label{display:grid;gap:5px;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#A0938A;font-weight:600}#hub-auth input{height:40px;border-radius:9px;border:1px solid #4B423C;background:#241F1B;color:#F3ECE4;font:inherit;font-size:14px;padding:0 12px}#hub-auth input:focus{outline:none;border-color:#E28F55;box-shadow:0 0 0 3px rgba(226,143,85,.18)}#hub-auth button{height:42px;border:0;border-radius:9px;background:#E28F55;color:#1A120C;font:inherit;font-size:15px;font-weight:600;cursor:pointer}#hub-auth button[disabled]{opacity:.6;cursor:wait}#hub-auth button.g{background:transparent;color:#D9CDC1;border:1px solid #4B423C}#hub-auth .r{display:flex;gap:10px;justify-content:space-between;align-items:center;font-size:13px;color:#A0938A}#hub-auth a{color:#F2C37B;cursor:pointer;text-decoration:none}#hub-auth .err{background:rgba(240,122,106,.15);border:1px solid rgba(240,122,106,.4);color:#F07A6A;padding:10px 12px;border-radius:9px;font-size:13px}#hub-auth .ok{background:rgba(127,203,154,.14);border:1px solid rgba(127,203,154,.4);color:#7FCB9A;padding:10px 12px;border-radius:9px;font-size:13px}#hub-auth ul.pol{margin:0;padding-left:18px;font-size:12.5px;color:#A0938A;display:grid;gap:3px}#hub-auth ul.pol li.y{color:#7FCB9A}#hub-auth .f{border-top:1px solid #3E3631;padding-top:12px;font-size:12px;color:#A0938A}`;
  async function shell(inner) { await domReady; let host = $("#hub-auth"); if (!host) { host = document.createElement("div"); host.id = "hub-auth"; const st = document.createElement("style"); st.textContent = css; document.head.appendChild(st); document.body.appendChild(host); } host.innerHTML = `<div class="c"><div class="b"><i></i><div><b>Analytics Hub</b><div style="font-size:12px;color:#A0938A">${esc(CFG.ACCOUNT_NAME || "")}</div></div></div>${inner}<div class="f">Passwords: at least ${POLICY.min} characters, upper and lower case letters, a number and a special character; changed every ${POLICY.rotateDays} days. Every action is written to the activity log.</div></div>`; host.style.display = "grid"; }
  function hide() { const h = $("#hub-auth"); if (h) h.style.display = "none"; }
  const errBox = m => `<div class="err">${esc(m)}</div>`, okBox = m => `<div class="ok">${esc(m)}</div>`;
  async function fatal(title, text) { await shell(`<h1>${esc(title)}</h1><p>${esc(text)}</p>`); }
  const stub = () => { window.claude = {use: async () => null}; };
  if (!window.supabase || typeof window.supabase.createClient !== "function") { fatal("Sign-in service unavailable", "vendor/supabase.js did not load. Redeploy the hosting build; it ships this file next to index.html."); stub(); return; }
  if (!CFG.SUPABASE_URL || !CFG.SUPABASE_ANON_KEY || /YOUR-PROJECT|YOUR-ANON/.test(CFG.SUPABASE_URL + CFG.SUPABASE_ANON_KEY)) { fatal("Deployment is not configured", "SUPABASE_URL and SUPABASE_ANON_KEY are missing. Set the two repository variables and run the deploy again."); stub(); return; }
  const sb = window.supabase.createClient(CFG.SUPABASE_URL, CFG.SUPABASE_ANON_KEY, {auth: {persistSession: true, autoRefreshToken: true, detectSessionInUrl: true, flowType: "implicit"}});
  let session = null, profile = null, resolveAuth; const authReady = new Promise(r => resolveAuth = r);
  const policyCheck = pw => ({length: pw.length >= POLICY.min, lower: /[a-z]/.test(pw), upper: /[A-Z]/.test(pw), numbers: /\d/.test(pw), special: /[^A-Za-z0-9\s]/.test(pw)});
  const policyOk = pw => Object.values(policyCheck(pw)).every(Boolean);
  const polList = pw => { const c = policyCheck(pw); return `<ul class="pol"><li class="${c.length ? "y" : ""}">${POLICY.min}+ characters</li><li class="${c.lower && c.upper ? "y" : ""}">upper and lower case letters</li><li class="${c.numbers ? "y" : ""}">a number</li><li class="${c.special ? "y" : ""}">a special character</li></ul>`; };
  const busy = on => { const b = $("#a_go"); if (b) b.disabled = !!on; };
  const here = () => location.origin + location.pathname;

  async function viewSignIn(msg) { await shell(`<h1>Sign in</h1><p>Use the email and password you registered with. New here? <a data-v="register">Create an account</a>.</p>${msg || ""}<label>Email<input id="a_email" type="email" autocomplete="username"></label><label>Password<input id="a_pw" type="password" autocomplete="current-password"></label><button id="a_go">Sign in</button><div class="r"><a data-v="forgot">Forgot password?</a><a data-v="register">Create an account</a></div>`); const go = async () => { busy(true); const {error} = await sb.auth.signInWithPassword({email: $("#a_email").value.trim(), password: $("#a_pw").value}); if (error) return viewSignIn(errBox(error.message)); }; $("#a_go").onclick = go; $("#a_pw").onkeydown = e => { if (e.key === "Enter") go(); }; }
  async function viewRegister(msg, keep) { await shell(`<h1>Create your account</h1><p>Register once. The admin approves your profile and assigns your role and workspaces; you can come back any time, approval does not need you online.</p>${msg || ""}<label>Name<input id="a_name" autocomplete="name" value="${esc(keep?.name || "")}"></label><label>Work email<input id="a_email" type="email" autocomplete="username" value="${esc(keep?.email || "")}"></label><label>Password<input id="a_pw" type="password" autocomplete="new-password"></label><div id="a_pol">${polList("")}</div><button id="a_go">Create account</button><div class="r"><a data-v="signin">Back to sign in</a></div>`); $("#a_pw").oninput = () => { $("#a_pol").innerHTML = polList($("#a_pw").value); }; $("#a_go").onclick = async () => { const name = $("#a_name").value.trim(), email = $("#a_email").value.trim(), pw = $("#a_pw").value; const keepv = {name, email}; if (!name) return viewRegister(errBox("Enter your name."), keepv); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return viewRegister(errBox("Enter a valid email address."), keepv); if (!policyOk(pw)) return viewRegister(errBox("The password does not meet the policy below."), keepv); busy(true); const {data, error} = await sb.auth.signUp({email, password: pw, options: {data: {name}, emailRedirectTo: here()}}); if (error) return viewRegister(errBox(error.message), keepv); if (data && data.session) { session = data.session; return start(); } viewSignIn(okBox("Account created. Confirm it from the email we just sent, then sign in. Your access request is already in the admin's queue.")); }; }
  async function viewForgot(msg) { await shell(`<h1>Reset password</h1><p>We email a reset link; it opens this page so you can set a new password.</p>${msg || ""}<label>Email<input id="a_email" type="email" autocomplete="username"></label><button id="a_go">Send reset link</button><div class="r"><a data-v="signin">Back to sign in</a></div>`); $("#a_go").onclick = async () => { busy(true); const {error} = await sb.auth.resetPasswordForEmail($("#a_email").value.trim(), {redirectTo: here()}); viewForgot(error ? errBox(error.message) : okBox("If that address has an account, a reset link is on its way.")); }; }
  async function viewNewPassword(reason) { await shell(`<h1>Set a new password</h1><p>${esc(reason)}</p><label>New password<input id="a_pw" type="password" autocomplete="new-password"></label><div id="a_pol">${polList("")}</div><button id="a_go">Save password</button>`); $("#a_pw").oninput = () => { $("#a_pol").innerHTML = polList($("#a_pw").value); }; $("#a_go").onclick = async () => { const pw = $("#a_pw").value; if (!policyOk(pw)) return viewNewPassword("The password does not meet the policy below."); busy(true); const {error} = await sb.auth.updateUser({password: pw}); if (error) return viewNewPassword(error.message); try { await sb.from("profiles").update({password_changed_at: new Date().toISOString()}).eq("id", session.user.id); } catch (_) {} await start(true); }; }
  document.addEventListener("click", e => { const a = e.target.closest("#hub-auth [data-v]"); if (!a) return; e.preventDefault(); ({signin: viewSignIn, register: viewRegister, forgot: viewForgot})[a.dataset.v](); });

  async function loadProfile() { const uid = session.user.id; let {data, error} = await sb.from("profiles").select("*").eq("id", uid).maybeSingle(); if (!data && !error) { const ins = await sb.from("profiles").insert({id: uid, email: session.user.email || "", name: session.user.user_metadata?.name || ""}).select("*").maybeSingle(); data = ins.data; } profile = data || null; }
  let starting = false;
  async function start(afterPw) { if (starting) return; starting = true; try { await domReady; const {data} = await sb.auth.getSession(); session = data.session; if (!session) return viewSignIn(); await loadProfile(); if (!profile) return fatal("Profile unavailable", "Your account exists but its profile row could not be read or created. Ask the admin to check the profiles table."); if (!afterPw && profile.password_changed_at && (Date.now() - new Date(profile.password_changed_at)) / 864e5 > POLICY.rotateDays) return viewNewPassword(`Your password is older than ${POLICY.rotateDays} days. Choose a new one to continue.`); hide(); resolveAuth(); } finally { starting = false; } }
  sb.auth.onAuthStateChange((ev, s) => { if (ev === "PASSWORD_RECOVERY") { session = s; viewNewPassword("Choose a new password for your account."); } else if (ev === "SIGNED_IN" && !session) { start(); } else if (ev === "SIGNED_OUT") { session = null; profile = null; location.reload(); } });

  // ---------- storage
  const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const mkErr = (code, message) => { const e = new Error(message || code); e.code = code; return e; };
  const fail = e => { throw mkErr(e && e.code === "42501" ? "permission_denied" : "invalid_argument", e && e.message); };
  const DEF_ACCESS = () => ({workspaces: "all", capabilities: {}});
  const ROW_KEYS = ["id", "email", "name", "team", "timezone", "role", "status", "access", "disabled", "claimed_user_id", "password_changed_at", "created_at", "updated_at"];
  const rowToUser = r => ({...(r.data || {}), id: r.id, email: r.email, name: r.name || "", team: r.team || "", timezone: r.timezone || "America/New_York", role: r.role, status: r.status === "paused" ? "active" : r.status, disabled: r.status === "paused", access: r.access || DEF_ACCESS(), claimed_user_id: r.id, password_changed_at: r.password_changed_at, created_at: r.created_at, updated_at: r.updated_at});
  const userToRow = (id, o) => { const data = {}; for (const k in o) if (!ROW_KEYS.includes(k)) data[k] = o[k]; return {id, email: o.email || "", name: o.name || "", team: o.team || "", timezone: o.timezone || "America/New_York", role: o.role || "viewer", status: o.disabled ? "paused" : (o.status || "requested"), access: o.access || DEF_ACCESS(), data}; };
  async function setUser(id, obj) { const target = obj.claimed_user_id || (UUID.test(id) ? id : null); if (!target) { const {error} = await sb.from("docs").upsert({collection: "users", id, data: obj, updated_at: new Date().toISOString()}); if (error) fail(error); return; } const {id: _id, ...patch} = userToRow(target, obj); const up = await sb.from("profiles").update(patch).eq("id", target).select("id"); if (up.error) fail(up.error); if (up.data && up.data.length) return; const ins = await sb.from("profiles").insert({id: target, ...patch}); if (ins.error) fail(ins.error); }
  async function getUser(id) { if (UUID.test(id)) { const {data, error} = await sb.from("profiles").select("*").eq("id", id).maybeSingle(); if (error) fail(error); if (data) return {exists: true, id: data.id, data: () => rowToUser(data)}; } const {data, error} = await sb.from("docs").select("data").eq("collection", "users").eq("id", id).maybeSingle(); if (error) fail(error); return {exists: !!data, id, data: () => data ? data.data : undefined}; }
  async function delUser(id) { const {error} = UUID.test(id) ? await sb.from("profiles").delete().eq("id", id) : await sb.from("docs").delete().eq("collection", "users").eq("id", id); if (error) fail(error); }
  async function listUsers() { const {data, error} = await sb.from("profiles").select("*"); if (error) fail(error); const rows = (data || []).map(rowToUser); const emails = new Set(rows.map(r => String(r.email || "").toLowerCase())); let extra = []; try { const q = await sb.from("docs").select("id,data").eq("collection", "users"); extra = (q.data || []).map(r => ({...(r.data || {}), id: r.id})).filter(u => !u.claimed_user_id && !emails.has(String(u.email || "").toLowerCase())); } catch (_) {} return [...rows, ...extra]; }
  async function listDocs(name) { const out = []; let from = 0; for (;;) { const {data, error} = await sb.from("docs").select("id,data").eq("collection", name).order("id").range(from, from + 999); if (error) fail(error); out.push(...(data || [])); if (!data || data.length < 1000) break; from += 1000; } return out.map(r => ({id: r.id, ...(r.data || {})})); }
  const dbNs = Object.freeze({
    doc: path => { const [collection, ...rest] = String(path).split("/"); const id = rest.join("/"); const users = collection === "users"; return Object.freeze({
      set: async obj => { if (users) return setUser(id, obj); const {error} = await sb.from("docs").upsert({collection, id, data: obj, updated_at: new Date().toISOString()}); if (error) fail(error); },
      get: async () => { if (users) return getUser(id); const {data, error} = await sb.from("docs").select("data").eq("collection", collection).eq("id", id).maybeSingle(); if (error) fail(error); return {exists: !!data, id, data: () => data ? data.data : undefined}; },
      delete: async () => { if (users) return delUser(id); const {error} = await sb.from("docs").delete().eq("collection", collection).eq("id", id); if (error) fail(error); }}); },
    collection: name => Object.freeze({get: async () => { const rows = name === "users" ? await listUsers() : await listDocs(name); return {docs: rows.map(r => ({id: r.id, data: () => r}))}; }})
  });
  const meObj = () => ({id: session.user.id, name: (profile && profile.name) || session.user.user_metadata?.name || "", email: session.user.email || null});
  const userNs = Object.freeze({id: async () => session.user.id, me: async () => meObj(), self: async () => meObj(), isOwner: async () => !!(profile && profile.role === "admin" && profile.status === "active"), canEdit: async () => !!(profile && profile.status === "active"), can: async () => !!(profile && profile.status === "active"), profiles: async ids => { const list = Array.isArray(ids) ? ids : []; const out = Object.fromEntries(list.map(i => [i, {id: i, name: ""}])); try { const {data} = await sb.from("profiles").select("id,name").in("id", list.filter(i => UUID.test(i))); (data || []).forEach(r => { out[r.id] = {id: r.id, name: r.name || ""}; }); } catch (_) {} return out; }});
  const downloadsNs = Object.freeze({save: async ({filename, data}) => { const blob = data instanceof Blob ? data : new Blob([data]); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = filename || "download"; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 2000); }});
  window.claude = {use: async name => { if (name === "db") { await authReady; return dbNs; } if (name === "user") { await authReady; return userNs; } if (name === "downloads") return downloadsNs; return null; }};
  window.HOSTED = {name: "supabase", resetPassword: email => sb.auth.resetPasswordForEmail(email, {redirectTo: here()}).then(({error}) => { if (error) throw error; }), signOut: () => sb.auth.signOut(), policy: POLICY, profile: () => profile, session: () => session, reloadProfile: loadProfile};
  start();
})();
