const {JSDOM, VirtualConsole} = require("jsdom"); const fs = require("fs");
const html = fs.readFileSync(__dirname + "/../analytics-hub.html", "utf8").replace(/<script src="https:[^"]+"><\/script>/, "").replace(/<link[^>]+fonts[^>]*>/g, "");
const errors = []; const vc = new VirtualConsole(); vc.on("jsdomError", e => errors.push(String(e.message||e).slice(0,300)));
const dom = new JSDOM(html, {runScripts: "dangerously", url: "https://example.test/#datorama", virtualConsole: vc, beforeParse(w) { w.XLSX = require("xlsx"); w.confirm = () => true; w.prompt = () => ""; }});
const w = dom.window;
w.eval(`DB = {doc: () => ({set: async () => {}})}; USER={id:"u1",name:"Joe Benson",owner:true}; window.claude = {use: async () => null};`);
const D = JSON.parse(fs.readFileSync(__dirname + "/seed.json", "utf8"));
w.__D = D; w.eval(`for (const k in window.__D) { if (!S[k]) S[k] = []; S[k].push(...window.__D[k]); }`);
(async () => { try {
  const out = {};
  out.cboe = w.eval(`(() => { const cid = live("clients").find(c => c.client_name === "Cboe").id; V.ws = cid; return {cid, streams: live("dat_streams").filter(s => sameWs(s.client_id, cid)).length, docs: wsDocs(cid).length, group: groupOf(cid)}; })()`);
  out.qa = w.eval(`(() => { const cid = V.ws; const header=["Day","Data Stream","PMI Media Buy Package","Media Buy Name","PMI Buying Region","PMI Media Buy Site Name","PMI Funding Source","PMI Free Form","PMI Cost Method","PMI Plan Spend","PMI Total Spend v2","PMI Actualized Spend","PMI Impressions","PMI Month Status","PMI Country"]; const P = live("mplans").find(m => m.format === "multi_region"); const rows = []; for (const l of P.lines.slice(0, 80)) for (const [m, v] of Object.entries(l.months || {})) { if (!v) continue; rows.push({"Day": m + "-15", "Data Stream": l.source === "prisma" ? "Google DFA Site Direct" : "TotalConnect - Vendor Data", "PMI Media Buy Package": l.is_package ? "1 - " + l.placement : "0 - No package", "Media Buy Name": l.name_raw || l.placement, "PMI Buying Region": l.region === "NAMR" ? "AMER" : l.region, "PMI Media Buy Site Name": l.partner, "PMI Funding Source": l.lob, "PMI Free Form": l.placement, "PMI Cost Method": l.buy, "PMI Plan Spend": v, "PMI Total Spend v2": Math.round(v * 0.95 * 100) / 100, "PMI Actualized Spend": m < "2026-08" ? v : 0, "PMI Impressions": Math.round((l.impressions || 0) / 9), "PMI Month Status": m < "2026-08" ? "Closed" : "Open", "PMI Country": l.market || "US"}); } const Vd = qaValidate(header, rows, cid); const o = {rows: rows.length, checks: Vd.checks.map(c => c.n + ":" + (c.ok ? "ok" : "FAIL ") + c.detail)}; if (!Vd.blocked) { const R = qaTiers(Vd, cid); o.flags = R.flags.map(f => "T" + f.tier + " " + f.code + " " + (f.ok ? "ok" : "FLAG") + " · " + f.actual); o.status = qaRunStatus(Vd, R, {}); o.recon = R.recon.filter(r => !r.informational).map(r => r.scope + " " + r.key + ": " + Math.round(r.actual) + " vs " + Math.round(r.target)); const run = {id: "r1", client_id: "cboe", status: o.status, file: "t.csv", ts: new Date().toISOString(), checks: Vd.checks, flags: R.flags, recon: R.recon, totals: R.totals, accepted: {}, overrides: {}, date_range: [Vd.minD, Vd.maxD], streams: Vd.streams, rows_n: rows.length, b6: "march-august", created_at: "2026-09-28T00:00:00.000Z", updated_at: "2026-09-28T00:00:00.000Z"}; const sheets = qaFlowchartSheets(run, {rows: Vd.body, C: Vd.C}, cid); o.sheets = sheets.map(s => s[0] + ":" + s[1].length); o.brandHead = sheets[0][1].slice(3, 10); S.qa_runs.push(run); V.qaRows = {run_id: "r1", header, rows: Vd.body, C: Vd.C}; window.__run = run; } return o; })()`);
  for (const mode of ["qa", "streams", "taxonomy", "regions", "docs", "queue"]) { try { w.eval(`V.datMode = "${mode}"; V.mpOpen = null; location.hash = "datorama"; render();`); out["dat_" + mode] = w.document.querySelector("#main").textContent.length + (mode === "qa" ? " · " + (w.document.querySelector(".banner .st")?.textContent || "no banner") : ""); } catch (e) { out["dat_" + mode] = "ERR " + e.message; } }
  // versions + audiences + plans list
  w.eval(`V.ws = "epdopecy"; V.mpOpen = "8uwdztss_v2"; V.mpTab = "versions"; location.hash = "plans"; render();`); out.versions = w.document.querySelector("#main").textContent.length;
  w.eval(`V.mpOpen = null; render();`); out.plansList = w.document.querySelectorAll("#main table tbody tr").length;
  w.eval(`V.ws = "r5u1yv98"; location.hash = "audiences"; render();`); out.audiences = w.document.querySelector("#main").textContent.length; out.audSeg = w.document.querySelector("#main h2")?.textContent;
  fs.writeFileSync("qa_run_seed.json", JSON.stringify(w.eval("window.__run")));
  console.log(JSON.stringify(out, null, 1)); console.log("ERRORS", errors.slice(0, 5)); process.exit(0);
} catch (e) { console.error("ERR", e.stack); process.exit(1); } })();
